version: 2.1
jobs:
  hello_world:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: echo "Hello World"
  yarn:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn global add node-gyp && yarn install
      - run: npm-v1-dependencies-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  build_test:
    jobs:
      - hello_world
      - yarn
