version: 2.1
workflows:
  workflow:
    jobs:
      - hello1
      - yarn1
jobs:
  hello1:
    docker:
      - image: 'circleci/node:12'
    steps:
      - checkout # check out the code in the project directory
      - run:
        command: 'echo ok'
        name: 'Hello World'
  yarn1:
    docker:
      - image: 'circleci/node:12'
    steps:
      - checkout
      - restore_cache:
        key: yarn-v1-packages-{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          keys: yarn-v1-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
