version: 2.1
jobs:
  job1:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: echo "Hello World"
  job2:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn global add node-gyp && yarn install
      - run: npm-v1-dependencies-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  build_test:
    jobs:
      - job1
      - job2
