version: 2.1
jobs:

  build:
    docker: &shared_docker
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: npm-v2-dependencies-{{ checksum "yarn.lock" }}

  lint:
    docker: *shared_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint && yarn format:check

  test:
    docker: *shared_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test:ci

  e2etest:
    docker:
      - image: cimg/node:12.18.4
        environment:
          DATABASE_URL: postgres://antoine_mortelier:pwd@localhost:5432/psdb
          JWT_SECRET: some string yo want
          API_PORT: 3000
          API_HOST: localhost
          API_PROTOCOL: http
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: antoine_mortelier
          POSTGRES_DB: psdb
          POSTGRES_PASSWORD: pwd

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test:e2e


workflows:
  version: 2
  build_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - e2etest:
          requires:
            - build