version: 2.1
jobs:
  cache: &shared-config
    docker:
      - image: circleci/node:12
  job1:
    <<: *shared-config
    steps:
      - checkout
      - run: echo "Hello World"
  job2:
    <<: *shared-config
    steps:
      - checkout
      - run: echo "Hello Man"

workflows:
  version: 2
  build_test:
    jobs:
      - job1
      - job2
